<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFkWj2rw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFkWj2rw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFkWj2rw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFkWj2rw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFkWj2rw\App_KernelDevDebugContainer([
    'container.build_hash' => 'FkWj2rw',
    'container.build_id' => '2a303d02',
    'container.build_time' => 1705915891,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFkWj2rw');
