<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_lucky_number' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky/number']], [], [], []],
    'app_lucky_aviso' => [[], ['_controller' => 'App\\Controller\\LuckyController::aviso'], [], [['text', '/lucky/aviso']], [], [], []],
    'app_coin_number' => [[], ['_controller' => 'App\\Controller\\coinController::number'], [], [['text', '/coin/coiner']], [], [], []],
];
