<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEw5C4EL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEw5C4EL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEw5C4EL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEw5C4EL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEw5C4EL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ew5C4EL',
    'container.build_id' => 'b59ef199',
    'container.build_time' => 1703756874,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEw5C4EL');
