version: '3'
services:
    db:
        image: mysql:latest
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password 
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: joan
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

        networks:
            - mynetwork

    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - .:/var/www/html
        networks:
            - mynetwork

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8000:80"
        environment:
          PMA_HOST: db
          PMA_USER: joan
          PMA_PASSWORD: root
          PMA_PORT: 3306
        networks:
            - mynetwork

networks:
    mynetwork:

volumes:
    mysql_data:
